#!/home/tohsaka/.version-fox/temp/1721491200-1128/python/bin/python
import utils
import config
import os
import handlers
from pathlib import Path
import sys

cfg = config.Config()

if __name__ == "__main__":
    if not config.LUA_VERSION_PATH.exists():
        os.makedirs(config.LUA_VERSION_PATH)
    versions = [version.replace(config.EXTENSION, "")
                for version in handlers.available()]
    current_verion = cfg.get("current")
    installed_versions = cfg.get("installed_versions")
    if current_verion is not None:
        print(f"Current version: {current_verion}")
    else:
        print("Any version of Lua has been installed")
    if len(sys.argv) > 1:
        if sys.argv[1] == "version":
            print("Available versions:")
            for version in versions:
                if current_verion == version:
                    print("*", version)
                    continue
                elif version in installed_versions:
                    print("+", version)
                    continue
                print(" ", version)
        elif sys.argv[1] == "download":
            if (len(sys.argv) < 3):
                print("Usage: python main.py download <version>")
                sys.exit(1)
            version = sys.argv[2]
            if version in versions and not Path.joinpath(config.LUA_VERSION_PATH, version).exists():
                handlers.install(version)
                os.remove(utils.get_lua_version_path(version))
            else:
                print("Invalid version or version already exists")
        elif sys.argv[1] == "init":
            if (len(sys.argv) < 3):
                print("Usage: python main.py init <shell>")
            elif (len(sys.argv) == 3):
                handlers.shell_init(sys.argv[2])
        elif sys.argv[1] == "list":
            handlers.get_install_list()
        elif sys.argv[1] == "use":
            if (len(sys.argv) < 3):
                print("Usage: python lvm.py use <version>")
                sys.exit(1)
            version = sys.argv[2]
            if version in installed_versions:
                handlers.use(version)
            else:
                print(f"The version:{sys.argv[2]} is not installed")
        elif sys.argv[1] == "remove":
            if (len(sys.argv) < 3):
                print("Usage: python lvm.py remove <version>")
                sys.exit(1)
            version = sys.argv[2]
            handlers.uninstall(version)
        elif sys.argv[1] == "help":
            print("Usage: python lvm.py <cmd>")
            print("  Available commands:")
            print("    version: list available versions")
            print("    download <version>: download and install lua version,'+' means installed version, '*' means current version")
            print("    init <shell>: initialize lua version")
            print("    list: list installed versions")
            print("    use <version>: use lua version")
            print("    remove <version>: remove lua version")

    else:
        print("Usage: python lvm.py <cmd>")
        print("  Available commands:")
        print("    version: list available versions")
        print("    download <version>: download and install lua version,'+' means installed version, '*' means current version")
        print("    init <shell>: initialize lua version")
        print("    list: list installed versions")
        print("    use <version>: use lua version")
        print("    remove <version>: remove lua version")
